### PR TITLE
stop rendering when we reaching batch size

### PR DESCRIPTION
**Pull request by ethersage**
Trying to solve #106 @getkey @tehdb.

I think this only happens for a very specific issue on batch boundary. Working on a test for that if anyone has any ideas.

-----

The maintainers of this repo require that all pull request submitters adhere to the following:

- [x] I have read and will comply with the [contribution guidelines](https://github.com/FormidableLabs/rapscallion/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] I have read and will comply with the [code of conduct](https://github.com/FormidableLabs/rapscallion/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by ethersage** [comment]
I think I have a test for it.

**Comment by ethersage** [comment]
I think I have a test for the issue, but turns out I haven't fixed it yet.

**Comment by ethersage** [comment]
Seems to work! @divmain Ready to go.

**Comment by getkey** [comment]
That fixed the issue on my project. Thanks!

**Pull request merged**
