### PR TITLE
Add support for rendering factory components

### PR DESCRIPTION
**Pull request by nyobe**
I'm not sure how common of a requirement this is, but it's something I ran into while trying to get Relay to render. Essentially "factory components" are functions that return an instance of a component, rather than a react node. Currently RelayContainers are lazily constructed using a factory component, but since the factory returns a component rather than a node, it ends up causing a `Unknown node of type: undefined` type error when Rapscallion attempts to traverse the result.

Unfortunately as far as I know it's impossible to know ahead of time whether a function is a factory component without checking its result. React supports this by essentially separating the shouldConstruct check from the shouldCallRender check. See https://github.com/facebook/react/blob/v15.4.2/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L199-L211

Ref: https://github.com/facebook/react/issues/8702#issuecomment-270912678

### CODE REVIEW

**Comment by tizmagik** [comment]
I just ran into this as well. Thanks for tracking down the root cause @nyobe I wasn't sure what exactly was producing the error.

**Comment by nyobe** [comment]
Hehe, yeah I wasn't sure what to do about that. What do you think about splitting it into two helpers, `constructComponent` and `renderComponentInstance`? Does this hurt readability?

**Comment by nyobe** [comment]
Thanks!

**Comment by tizmagik** [comment]
Yay nice job! 😁

**Comment by divmain** [comment]
Awesome!  Thanks again @nyobe.  I'll be cutting a release in the next day or so.

**Comment by tizmagik** [comment]
Sorry to bump @divmain but any ETA on a release? 🙏

**Comment by divmain** [comment]
Sorry for the wait - I've been flooded from the [freactal](https://github.com/FormidableLabs/freactal) release.  The fix in this PR is published as part of v2.1.7.  Let me know if you run into issues!

**Comment by tizmagik** [comment]
Thanks @divmain , much appreciated! Also congrats on the freactal release! 🎉

**Pull request merged**
