### PR TITLE
Fix: false component rendering

### PR DESCRIPTION
**Pull request by fleg**
Do not emit when node undefined or true

-----

The maintainers of this repo require that all pull request submitters adhere to the following:

- [x] I have read and will comply with the [contribution guidelines](https://github.com/FormidableLabs/rapscallion/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] I have read and will comply with the [code of conduct](https://github.com/FormidableLabs/rapscallion/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by ethersage** [comment]
@fleg Please see the new maintainerd subject requirements PR check. Thanks!

**Comment by fleg** [comment]
looks like it's just hang at body check

**Comment by ethersage** [comment]
@divmain Looks like I lost merge access 😿

**Comment by ethersage** [comment]
image

**Comment by divmain** [comment]
Total failure to respond, on my part - personal life took over for awhile, but I have some time to spend on all of this again.  @ethersage, your permissions never changed so you should have write access.  I've changed them and set them back again.  Please let me know if that works.  In the mean-time, I'll merge this myself.

**Pull request merged**
