### PR TITLE
fix elements discrepancies

### PR DESCRIPTION
**Pull request by fleg**
with tests from #58 

- [x] ~~remove dup tests from special-cases.js~~

### CODE REVIEW

**Comment by fleg** [comment]
rebased

**Comment by pristas-peter** [comment]
hi, I had some checksum failures on text nodes, when server render -> text comment and react on client not, but when I changed the condition to numChildren !== undefined, errors are gone, like this:

```
+function emitText ({ seq, text, numChildren, isNewlineEatingTag }) {
    const hasSiblings = numChildren !== undefined
  
    if (hasSiblings) {
      seq.emit(() => REACT_TEXT_START);
    }
  
 +  if (isNewlineEatingTag && text.charAt(0) === "\n") {
 +    text = `\n${text}`;
 +  }
 +

```

Can you have a look why is this working? Thanks
...

**Comment by fleg** [comment]
can you provide minimal test case?

**Comment by pristas-peter** [comment]
Ok, I have found the problem, react will render text comment node, when children are array of one text node, whether the server will not:


```
class View2 extends React.PureComponent { 
    render() {
        return (
            <span>
                {this.props.children}
            </span>
        );
    }
}
class View extends React.PureComponent {
    render() {

        return (
            <View2>
                {['Test']}
            </View2>
        );
    }
}

```

**Comment by fleg** [comment]
@pristas-peter fixed! thank you for report

**Comment by pristas-peter** [comment]
thanks, you're welcome

**Comment by pristas-peter** [comment]
const hasSiblings = new Boolean(numChildren); now gives errors for single node text elements

const hasSiblings = numChildren !== undefined; gives different results

**Comment by fleg** [comment]
example, please

**Pull request merged**
