### PR TITLE
replace babel-preset-latest with babel-preset-env

### PR DESCRIPTION
**Pull request by pwmckenna**
Saw this warning and just followed directions :)
screen shot 2017-04-03 at 9 37 59 am

### CODE REVIEW

**Comment by baer** [comment]
Thanks so much for the PR @pwmckenna! `babel-preset-env` is a great project and this seems like a very appropriate addition since it's the direction that the babel team really wants folks to go. The way that plugin works is that you specify the environments that you'd like to support. Without the extra config, it doesn't actually apply any transformations. Below is an example. If you'd like to try to get this PR up to date, we'd love the contribution.

```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }]
  ]
}
```

**Comment by aweary** [comment]
More specifically, since this is meant to run on the server, I think we can configure it based on the oldest supported version of Node:

```js
{
  "presets": [
    ["env", {
      "targets": {
        "node": 4
      }
    }]
  ]
}
```

I'm not sure if 4.x is actually the oldest supported version, do you know @baer?

**Comment by baer** [comment]
Sorry, that was just a copy-pasta example of config from the `babel-preset-env` project page and was not meant to be the actual config that this project should use.

It looks like [Node 6 is the Lowest Supported Version](https://github.com/FormidableLabs/rapscallion/blob/master/package.json#L59) which makes sense with 8 coming out so soon. My guess is that [`"node": "current"`](https://github.com/babel/babel-preset-env#targetsnode) would be appropriate or, if you wanted to match engines (which is a good idea) then maybe `"node": 6`

**Comment by ryan-roemer** [comment]
@baer -- The `package.json:engine` should be changed, as the babel thing is to get us support for nodes less than 6.

Offhand, on quick skim looks like we support all nodes in `https://unpkg.com/rapscallion@2.1.6/lib/` right now. Maybe just remove the engines restriction altogether, update our preset to node 4 (or earlier if there's demand) and be done with it...

**Comment by baer** [comment]
IMO we shouldn't support versions of Node that they no longer support themselves. We could just track [LTS](https://github.com/nodejs/LTS) which would be 4.x until April of next year. I'm on borad with Node 4 + updating the engines

**Comment by divmain** [comment]
Doing some house cleaning on these stale PRs.  I updated to `babel-preset-env` with a Node target of `4`.

**Pull request closed without merging**
